// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDk2q6VSUaJHx0O_wBmMHTWKxqtQ0ZW10',
    appId: '1:101895701888:web:8a9fc399e22d1541916d65',
    messagingSenderId: '101895701888',
    projectId: 'drivetogether-74ff1',
    authDomain: 'drivetogether-74ff1.firebaseapp.com',
    storageBucket: 'drivetogether-74ff1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZwbP_SDTdF_42LNEMjVvrEUmAlo861us',
    appId: '1:101895701888:android:b7e3b2efea67d14b916d65',
    messagingSenderId: '101895701888',
    projectId: 'drivetogether-74ff1',
    storageBucket: 'drivetogether-74ff1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl5j8dHP5daoSxsw3oXmAcyWsW2xEZYII',
    appId: '1:101895701888:ios:39709dbe0762d19b916d65',
    messagingSenderId: '101895701888',
    projectId: 'drivetogether-74ff1',
    storageBucket: 'drivetogether-74ff1.appspot.com',
    iosBundleId: 'com.example.drivetogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl5j8dHP5daoSxsw3oXmAcyWsW2xEZYII',
    appId: '1:101895701888:ios:39709dbe0762d19b916d65',
    messagingSenderId: '101895701888',
    projectId: 'drivetogether-74ff1',
    storageBucket: 'drivetogether-74ff1.appspot.com',
    iosBundleId: 'com.example.drivetogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDk2q6VSUaJHx0O_wBmMHTWKxqtQ0ZW10',
    appId: '1:101895701888:web:2250d9533e0c5b30916d65',
    messagingSenderId: '101895701888',
    projectId: 'drivetogether-74ff1',
    authDomain: 'drivetogether-74ff1.firebaseapp.com',
    storageBucket: 'drivetogether-74ff1.appspot.com',
  );
}
